# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzy_HW2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(12, 132, 289, 289))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(12, 108, 241, 37))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.theta_s_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.theta_s_edit.setObjectName("theta_s_edit")
        self.horizontalLayout_2.addWidget(self.theta_s_edit)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.premise_xn2a = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.premise_xn2a.setObjectName("premise_xn2a")
        self.horizontalLayout_2.addWidget(self.premise_xn2a)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(12, 192, 241, 37))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.u_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.u_Edit.setObjectName("u_Edit")
        self.horizontalLayout_3.addWidget(self.u_Edit)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.consequent_gna = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.consequent_gna.setObjectName("consequent_gna")
        self.horizontalLayout_3.addWidget(self.consequent_gna)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(12, 24, 241, 37))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.theta_s_edit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.theta_s_edit_3.setObjectName("theta_s_edit_3")
        self.horizontalLayout_4.addWidget(self.theta_s_edit_3)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.premise_xn1a = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.premise_xn1a.setObjectName("premise_xn1a")
        self.horizontalLayout_4.addWidget(self.premise_xn1a)
        self.pushButton_result_a = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_result_a.setGeometry(QtCore.QRect(168, 240, 97, 37))
        self.pushButton_result_a.setObjectName("pushButton_result_a")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(12, 60, 193, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.edit_x1a_0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edit_x1a_0.setObjectName("edit_x1a_0")
        self.horizontalLayout.addWidget(self.edit_x1a_0)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.edit_x1a_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edit_x1a_1.setObjectName("edit_x1a_1")
        self.horizontalLayout.addWidget(self.edit_x1a_1)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(12, 144, 193, 25))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.edit_x2a_0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.edit_x2a_0.setObjectName("edit_x2a_0")
        self.horizontalLayout_8.addWidget(self.edit_x2a_0)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.edit_x2a_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.edit_x2a_1.setObjectName("edit_x2a_1")
        self.horizontalLayout_8.addWidget(self.edit_x2a_1)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(12, 252, 145, 25))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_a = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.comboBox_a.setObjectName("comboBox_a")
        self.comboBox_a.addItem("")
        self.comboBox_a.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_a)
        self.pushButton_plot_a = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_plot_a.setObjectName("pushButton_plot_a")
        self.horizontalLayout_6.addWidget(self.pushButton_plot_a)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(12, 444, 289, 289))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_result_b = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_result_b.setGeometry(QtCore.QRect(156, 240, 109, 37))
        self.pushButton_result_b.setObjectName("pushButton_result_b")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(12, 24, 241, 37))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_10.addWidget(self.label_27)
        self.theta_s_edit_11 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.theta_s_edit_11.setObjectName("theta_s_edit_11")
        self.horizontalLayout_10.addWidget(self.theta_s_edit_11)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_10.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_10.addWidget(self.label_29)
        self.premise_xn1b = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.premise_xn1b.setObjectName("premise_xn1b")
        self.horizontalLayout_10.addWidget(self.premise_xn1b)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(12, 144, 193, 25))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        spacerItem3 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.edit_x2b_0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.edit_x2b_0.setObjectName("edit_x2b_0")
        self.horizontalLayout_13.addWidget(self.edit_x2b_0)
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_13.addWidget(self.label_37)
        self.edit_x2b_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.edit_x2b_1.setObjectName("edit_x2b_1")
        self.horizontalLayout_13.addWidget(self.edit_x2b_1)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(12, 192, 241, 37))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.u_Edit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.u_Edit_3.setObjectName("u_Edit_3")
        self.horizontalLayout_12.addWidget(self.u_Edit_3)
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_12.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_12.addWidget(self.label_35)
        self.consequent_gnb = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.consequent_gnb.setObjectName("consequent_gnb")
        self.horizontalLayout_12.addWidget(self.consequent_gnb)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(12, 108, 241, 37))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_11.addWidget(self.label_30)
        self.theta_s_edit_12 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.theta_s_edit_12.setObjectName("theta_s_edit_12")
        self.horizontalLayout_11.addWidget(self.theta_s_edit_12)
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_11.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32)
        self.premise_xn2b = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.premise_xn2b.setObjectName("premise_xn2b")
        self.horizontalLayout_11.addWidget(self.premise_xn2b)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(12, 60, 193, 25))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.edit_x1b_0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.edit_x1b_0.setObjectName("edit_x1b_0")
        self.horizontalLayout_9.addWidget(self.edit_x1b_0)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.edit_x1b_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.edit_x1b_1.setObjectName("edit_x1b_1")
        self.horizontalLayout_9.addWidget(self.edit_x1b_1)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(12, 252, 133, 25))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_b = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.comboBox_b.setObjectName("comboBox_b")
        self.comboBox_b.addItem("")
        self.comboBox_b.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_b)
        self.pushButton_plot_b = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_plot_b.setObjectName("pushButton_plot_b")
        self.horizontalLayout_7.addWidget(self.pushButton_plot_b)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(324, 120, 697, 625))
        self.groupBox_3.setObjectName("groupBox_3")
        self.matplotlibwidget_result = MatplotlibWidget(self.groupBox_3)
        self.matplotlibwidget_result.setGeometry(QtCore.QRect(24, 24, 661, 469))
        self.matplotlibwidget_result.setObjectName("matplotlibwidget_result")
        self.groupBox_result_a = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_result_a.setGeometry(QtCore.QRect(36, 492, 289, 121))
        self.groupBox_result_a.setObjectName("groupBox_result_a")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_result_a)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(12, 24, 241, 96))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_a = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_a.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_a.setObjectName("verticalLayout_a")
        self.label_fx1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fx1.setObjectName("label_fx1")
        self.verticalLayout_a.addWidget(self.label_fx1)
        self.label_fx2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fx2.setObjectName("label_fx2")
        self.verticalLayout_a.addWidget(self.label_fx2)
        self.label_ha = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ha.setObjectName("label_ha")
        self.verticalLayout_a.addWidget(self.label_ha)
        self.label_ea = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ea.setObjectName("label_ea")
        self.verticalLayout_a.addWidget(self.label_ea)
        self.groupBox_result_b = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_result_b.setGeometry(QtCore.QRect(372, 492, 289, 121))
        self.groupBox_result_b.setObjectName("groupBox_result_b")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_result_b)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(12, 24, 241, 96))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_b = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_b.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_b.setObjectName("verticalLayout_b")
        self.label_fx1x1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_fx1x1.setObjectName("label_fx1x1")
        self.verticalLayout_b.addWidget(self.label_fx1x1)
        self.label_fx2x2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_fx2x2.setObjectName("label_fx2x2")
        self.verticalLayout_b.addWidget(self.label_fx2x2)
        self.label_hb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_hb.setObjectName("label_hb")
        self.verticalLayout_b.addWidget(self.label_hb)
        self.label_eb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_eb.setObjectName("label_eb")
        self.verticalLayout_b.addWidget(self.label_eb)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(24, 72, 160, 37))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.edit_e = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.edit_e.setObjectName("edit_e")
        self.horizontalLayout_5.addWidget(self.edit_e)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(24, 12, 709, 49))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.edit_equation = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.edit_equation.setObjectName("edit_equation")
        self.horizontalLayout_14.addWidget(self.edit_equation)
        self.pushButton_go = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.pushButton_go.setObjectName("pushButton_go")
        self.horizontalLayout_14.addWidget(self.pushButton_go)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "HW2 (a)"))
        self.label_15.setText(_translate("MainWindow", "前件部2"))
        self.theta_s_edit.setText(_translate("MainWindow", "x2"))
        self.label_20.setText(_translate("MainWindow", "fuzzyset數量"))
        self.label_13.setText(_translate("MainWindow", "："))
        self.premise_xn2a.setText(_translate("MainWindow", "125"))
        self.label_6.setText(_translate("MainWindow", "後件部"))
        self.u_Edit.setText(_translate("MainWindow", "g(x)"))
        self.label_21.setText(_translate("MainWindow", "fuzzyset數量"))
        self.label_11.setText(_translate("MainWindow", "："))
        self.consequent_gna.setText(_translate("MainWindow", "15625"))
        self.label_17.setText(_translate("MainWindow", "前件部1"))
        self.theta_s_edit_3.setText(_translate("MainWindow", "x1"))
        self.label_18.setText(_translate("MainWindow", "fuzzyset數量"))
        self.label_19.setText(_translate("MainWindow", "："))
        self.premise_xn1a.setText(_translate("MainWindow", "125"))
        self.pushButton_result_a.setText(_translate("MainWindow", "Plot_result"))
        self.label_3.setText(_translate("MainWindow", "範圍"))
        self.edit_x1a_0.setText(_translate("MainWindow", "-1"))
        self.label_4.setText(_translate("MainWindow", "："))
        self.edit_x1a_1.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "範圍"))
        self.edit_x2a_0.setText(_translate("MainWindow", "-1"))
        self.label_8.setText(_translate("MainWindow", "："))
        self.edit_x2a_1.setText(_translate("MainWindow", "1"))
        self.comboBox_a.setItemText(0, _translate("MainWindow", "x1"))
        self.comboBox_a.setItemText(1, _translate("MainWindow", "x2"))
        self.pushButton_plot_a.setText(_translate("MainWindow", "Plot_fuzzyset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "HW2 (b)"))
        self.pushButton_result_b.setText(_translate("MainWindow", "Plot_result"))
        self.label_27.setText(_translate("MainWindow", "前件部1"))
        self.theta_s_edit_11.setText(_translate("MainWindow", "x1"))
        self.label_28.setText(_translate("MainWindow", "fuzzyset數量"))
        self.label_29.setText(_translate("MainWindow", "："))
        self.premise_xn1b.setText(_translate("MainWindow", "5"))
        self.label_36.setText(_translate("MainWindow", "範圍"))
        self.edit_x2b_0.setText(_translate("MainWindow", "-1"))
        self.label_37.setText(_translate("MainWindow", "："))
        self.edit_x2b_1.setText(_translate("MainWindow", "1"))
        self.label_33.setText(_translate("MainWindow", "後件部"))
        self.u_Edit_3.setText(_translate("MainWindow", "g(x)"))
        self.label_34.setText(_translate("MainWindow", "fuzzyset數量"))
        self.label_35.setText(_translate("MainWindow", "："))
        self.consequent_gnb.setText(_translate("MainWindow", "25"))
        self.label_30.setText(_translate("MainWindow", "前件部2"))
        self.theta_s_edit_12.setText(_translate("MainWindow", "x2"))
        self.label_31.setText(_translate("MainWindow", "fuzzyset數量"))
        self.label_32.setText(_translate("MainWindow", "："))
        self.premise_xn2b.setText(_translate("MainWindow", "5"))
        self.label_9.setText(_translate("MainWindow", "範圍"))
        self.edit_x1b_0.setText(_translate("MainWindow", "-1"))
        self.label_10.setText(_translate("MainWindow", "："))
        self.edit_x1b_1.setText(_translate("MainWindow", "1"))
        self.comboBox_b.setItemText(0, _translate("MainWindow", "x1"))
        self.comboBox_b.setItemText(1, _translate("MainWindow", "x2"))
        self.pushButton_plot_b.setText(_translate("MainWindow", "Plot_fuzzyset"))
        self.groupBox_3.setTitle(_translate("MainWindow", "目標函數"))
        self.groupBox_result_a.setTitle(_translate("MainWindow", "12.2 (a)"))
        self.label_fx1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">max_f</span><span style=\" font-size:12pt; vertical-align:sub;\">x1</span><span style=\" font-size:12pt;\"> = 1.5</span></p></body></html>"))
        self.label_fx2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">max_f</span><span style=\" font-size:12pt; vertical-align:sub;\">x2</span><span style=\" font-size:12pt;\"> = 1.6</span></p></body></html>"))
        self.label_ha.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">ha = 0.01613</span></p></body></html>"))
        self.label_ea.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">error = 0.05</span></p></body></html>"))
        self.groupBox_result_b.setTitle(_translate("MainWindow", "12.3 (b)"))
        self.label_fx1x1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">max_f</span><span style=\" font-size:12pt; vertical-align:sub;\">x1x1</span><span style=\" font-size:12pt;\"> = 1.0</span></p></body></html>"))
        self.label_fx2x2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">max_f</span><span style=\" font-size:12pt; vertical-align:sub;\">x2x2</span><span style=\" font-size:12pt;\"> = 0.4</span></p></body></html>"))
        self.label_hb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">hb = 0.53452</span></p></body></html>"))
        self.label_eb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">error = 0.05</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">準確度e</span></p></body></html>"))
        self.edit_e.setText(_translate("MainWindow", "0.05"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">fuzzy近似方程式</span></p></body></html>"))
        self.edit_equation.setText(_translate("MainWindow", "0.5*x1**2 + 0.2*x2**2 + 0.7*x2 - 0.5*x1*x2"))
        self.pushButton_go.setText(_translate("MainWindow", "GO"))

from matplotlibwidget import MatplotlibWidget
